spring.application.name=neuromind-backend
spring.datasource.url=jdbc:postgresql://ep-tiny-shadow-ambx46yc-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AKEjJ8uXd2FG

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=neuromind2026SuperSecretKeyForJwtSigningChangeThis
jwt.expiration=36000000

logging.level.org.hibernate.SQL=DEBUG  

# Groq API Configuration
groq.api.key=${GROQ_API_KEY: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}